// ═══════════════════════════════════
//  INLINE STYLES (S object)
// ═══════════════════════════════════
const S = {
  screen:{minHeight:'100vh',background:'var(--dark)',paddingBottom:60},
  hdr:{background:'linear-gradient(180deg,var(--dark),var(--d2))',borderBottom:'2px solid var(--gold)',
    padding:'12px 16px 10px',textAlign:'center',position:'sticky',top:0,zIndex:100,
    boxShadow:'0 4px 20px rgba(0,0,0,.8)'},
  h1:{fontFamily:'Cinzel,serif',fontSize:'clamp(15px,5vw,22px)',fontWeight:900,color:'var(--gold)',
    letterSpacing:'.1em',textShadow:'0 0 20px rgba(201,168,76,.4)',lineHeight:1,margin:0},
  hsub:{fontSize:11,color:'var(--steel)',letterSpacing:'.2em',textTransform:'uppercase',marginTop:3},
  nav:{display:'flex',background:'var(--d2)',borderBottom:'1px solid rgba(201,168,76,.3)',overflowX:'auto',WebkitOverflowScrolling:'touch'},
  navBtn:(on)=>({flex:1,minWidth:66,padding:'10px 4px',background:on?'rgba(201,168,76,.05)':'none',
    border:'none',color:on?'var(--gold)':'var(--steel)',fontFamily:'Cinzel,serif',fontSize:10,
    letterSpacing:'.04em',cursor:'pointer',borderBottom:on?'2px solid var(--gold)':'2px solid transparent',
    whiteSpace:'nowrap',transition:'all .2s'}),
  page:{padding:13,maxWidth:600,margin:'0 auto'},
  card:{background:'var(--d2)',border:'1px solid rgba(201,168,76,.22)',borderRadius:4,padding:14,marginBottom:12,position:'relative'},
  cardTop:{position:'absolute',top:0,left:0,right:0,height:2,background:'linear-gradient(90deg,transparent,var(--blood),transparent)'},
  cardTitle:{fontFamily:'Cinzel,serif',fontSize:12,color:'var(--gold)',letterSpacing:'.1em',textTransform:'uppercase',marginBottom:12,display:'flex',alignItems:'center',gap:8,flexWrap:'wrap'},
  input:{width:'100%',background:'var(--d3)',border:'1px solid rgba(201,168,76,.28)',borderRadius:3,color:'var(--text)',fontFamily:'Crimson Pro,serif',fontSize:16,padding:'9px 11px',marginBottom:10,outline:'none',WebkitAppearance:'none',appearance:'none'},
  select:{width:'100%',background:'var(--d3)',border:'1px solid rgba(201,168,76,.28)',borderRadius:3,color:'var(--text)',fontFamily:'Crimson Pro,serif',fontSize:16,padding:'9px 11px',marginBottom:10,outline:'none',WebkitAppearance:'none',appearance:'none'},
  label:{display:'block',fontSize:11,color:'var(--steel)',letterSpacing:'.1em',textTransform:'uppercase',marginBottom:4},
  btn:(v='gold',sm=false)=>({
    display:'inline-flex',alignItems:'center',justifyContent:'center',gap:5,
    padding:sm?'6px 12px':'10px 14px',border:'none',borderRadius:3,
    fontFamily:'Cinzel,serif',fontSize:sm?10:11,letterSpacing:'.07em',cursor:'pointer',
    textTransform:'uppercase',width:sm?'auto':'100%',marginBottom:sm?0:8,
    ...(v==='red'?   {background:'linear-gradient(135deg,var(--blood),#6B0000)',color:'var(--gl)',border:'1px solid var(--blood)',boxShadow:'0 2px 8px rgba(139,0,0,.4)'}:{}),
    ...(v==='gold'?  {background:'linear-gradient(135deg,#7A5C1C,#5A3C0C)',color:'var(--gl)',border:'1px solid rgba(201,168,76,.5)'}:{}),
    ...(v==='green'? {background:'rgba(0,80,0,.4)',color:'#88FF88',border:'1px solid rgba(0,120,0,.5)'}:{}),
    ...(v==='danger'?{background:'rgba(139,0,0,.3)',color:'#FF6666',border:'1px solid rgba(139,0,0,.5)'}:{}),
    ...(v==='outline'?{background:'transparent',color:'var(--steel)',border:'1px solid rgba(201,168,76,.25)'}:{}),
    ...(v==='blue'?  {background:'rgba(0,60,120,.4)',color:'#88CCFF',border:'1px solid rgba(0,80,160,.5)'}:{}),
  }),
  infoGrid:{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:7,marginBottom:12},
  ib:{background:'var(--d3)',border:'1px solid rgba(201,168,76,.2)',borderRadius:3,padding:10,textAlign:'center'},
  ibVal:{fontFamily:'Cinzel,serif',fontSize:20,fontWeight:700,color:'var(--gold)',lineHeight:1},
  ibLbl:{fontSize:10,color:'var(--steel)',letterSpacing:'.1em',textTransform:'uppercase',marginTop:3},
  msg:{background:'rgba(201,168,76,.07)',border:'1px solid rgba(201,168,76,.22)',borderRadius:3,padding:'10px 12px',fontSize:13,color:'var(--text)',marginBottom:12,lineHeight:1.5},
  playerRow:{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'8px 12px',background:'var(--d3)',border:'1px solid rgba(201,168,76,.14)',borderRadius:3,marginBottom:6},
  badge:(c)=>({display:'inline-block',padding:'2px 8px',borderRadius:2,fontFamily:'Cinzel,serif',fontSize:10,letterSpacing:'.04em',
    ...(c==='rd'?{background:'rgba(139,0,0,.3)',color:'#FF8888',border:'1px solid rgba(139,0,0,.5)'}:{}),
    ...(c==='ok'?{background:'rgba(0,80,40,.4)',color:'#88FFBB',border:'1px solid rgba(0,120,60,.4)'}:{}),
    ...(c==='live'?{background:'rgba(0,100,0,.4)',color:'#88FF88',border:'1px solid rgba(0,140,0,.5)',animation:'pulse 2s infinite'}:{}),
  }),
  resBadge:(bp)=>({display:'inline-block',padding:'2px 6px',borderRadius:2,fontFamily:'Cinzel,serif',fontSize:10,letterSpacing:'.04em',marginTop:2,whiteSpace:'nowrap',
    ...(bp>10?{background:'rgba(0,100,0,.35)',color:'var(--win)',border:'1px solid rgba(0,140,0,.35)'}:{}),
    ...(bp===10?{background:'rgba(100,80,0,.3)',color:'var(--draw)',border:'1px solid rgba(150,120,0,.3)'}:{}),
    ...(bp<10?{background:'rgba(120,0,0,.3)',color:'var(--loss)',border:'1px solid rgba(160,0,0,.3)'}:{}),
  }),
  divider:{display:'flex',alignItems:'center',gap:8,margin:'10px 0',color:'var(--steel)',fontSize:10,letterSpacing:'.15em',textTransform:'uppercase'},
  pairCard:{background:'var(--d3)',border:'1px solid rgba(201,168,76,.18)',borderRadius:4,marginBottom:9},
  scoreInput:{width:'100%',background:'var(--d3)',border:'1px solid rgba(201,168,76,.3)',borderRadius:3,color:'var(--text)',fontFamily:'Crimson Pro,serif',fontSize:17,padding:'8px 4px',outline:'none',textAlign:'center',appearance:'none',WebkitAppearance:'none'},
  stTable:{width:'100%',borderCollapse:'collapse',fontSize:13},
  stTh:{fontFamily:'Cinzel,serif',fontSize:10,color:'var(--gold)',letterSpacing:'.06em',textTransform:'uppercase',padding:'6px 5px',borderBottom:'1px solid rgba(201,168,76,.3)',textAlign:'left'},
  stTd:{padding:'8px 5px',borderBottom:'1px solid rgba(255,255,255,.05)'},
  overlay:{position:'fixed',inset:0,background:'rgba(0,0,0,.9)',zIndex:200,display:'flex',alignItems:'center',justifyContent:'center',padding:20},
  modalBox:{background:'var(--d2)',border:'1px solid var(--gold)',borderRadius:4,padding:20,width:'100%',maxWidth:400,maxHeight:'90vh',overflowY:'auto'},
};
